### ISSUE TITLE
Please fix repo URL

### ISSUE THREAD

**Issue by pcav** [SIRS-CLS/mos-adeupa-ce#1]
it is currently 404
thanks

**Comment by Ailurupoda** [comment]
How can i do that ? I tried to update the zip file, but it seems it doesn't read the metadata file :/

I have droped the version and created a new one. And tried also to simply update the version using a new zip file, but it seems it's not working :/

EDIT : I edited directly in the graphic interface

**Comment by pcav** [comment]
Well done, thanks.

**Comment by pcav** [comment]
I can't see the change

**Comment by Ailurupoda** [comment]
Hmm that's weird.. I don't know how it works .. I change it using manage button and then edit

**Comment by pcav** [comment]
in, and it's still https://www.sirs-fr.com/

**Comment by Ailurupoda** [comment]
This Link is the link for the company WebSite.
There is a link on the github issue for the tracker option, and a link for the github repository for the repository option.

What should i put on the homepage then ?

EDIT : I've replace it by the gGitHub repository like i saw on other plugin

**Comment by pcav** [comment]
Sorry, I mixed with other plugins.
It's good now.

**Comment by Ailurupoda** [comment]
So i can keep the homepage url as : https://www.sirs-fr.com/ ? Or i still need to get the repository URL ?

**Comment by pcav** [comment]
Please use the repository URL. Thanks.

**Comment by Ailurupoda** [comment]
It's done

**Comment by pcav** [comment]
Merci
