### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [SIRS-CLS/mos-adeupa-ce#2]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by Ailurupoda** [comment]
It should be fine now, i've removes the .pyc, and the pcache folder. Do i need to remove the .py file generated with the .ui and .qrc file ? Are they generated automatically or it's fine taht i generated them ?

**Comment by pcav** [comment]
still there, e.g.
https://github.com/SIRS-CLS/mos-adeupa-ce/blob/master/mos_adeupa_ce/create_socle.pyc

**Comment by Ailurupoda** [comment]
Oh sorry, i changed it on the zip file, but not on the repository. Should be good now

**Comment by Ailurupoda** [comment]
I saw that the plugin has been approved. How do it work to get it from the QGIS plugin tab now ?
Do i still need to pass some step, or it just need a bit of tome ?

**Comment by pcav** [comment]
There is a cache server site, so it normally takes several minutes.
Please let us know in case it does not show up.

**Comment by Ailurupoda** [comment]
Great ! It works fine. Thanks :)
