### ISSUE TITLE
colonne sec.geo_section n'existe pas

### ISSUE THREAD

**Issue by sylvain0** [SIRS-CLS/mos-adeupa-ce#4]
Bonjour,

J'ai le message d'erreur suivant : 
```
File "C:/Users/mon_nom/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\mos_adeupa_ce\create_socle.py", line 1277, in createSocle
              self.socle_geom#12
             psycopg2.ProgrammingError: ERREUR: la colonne sec.geo_section n'existe pas
             LINE 11: ... Join plugin.pci_sectioncadastrale sec on sec.geo_se...
              ^
```
J'ai essayé sans succès de changer le nom de ma colonne geom en geo.

Merci

**Comment by Ailurupoda** [comment]
Bonjour,

Y a t'il eu des mises à jour de version du côté des données EDIGEO ?
Dans l'organisation des données EDIGEO, nous retrouvons une table *geo_parcelle* et une table *geo_section*. Dans chacune de ces table, le champ *geo_section* est présent, permettant ainsi de lier les deux tables.
Comment se présentent les données que vous possédez ?

**Comment by sylvain0** [comment]
Bonjour,

Merci pour votre réponse!
Je suis parti avec le PCI et du coup mes noms de champs sont différents.
J'ai renommé n_section en geo_section et je n'ai plus le message d'erreur.

Maintenant j'ai les erreurs liées au noms de champs de la table subdivision qui arrivent!

Que me conseillez-vous:
- continuer à corriger les noms de champs du PCI au compte goutte ou
- il faut absolument tout recommencer avec les données edigéo que je ne maitrise pas? 

Si je dois repartir avec les données edigeo pouvez-vous m'orienter vers une méthode ou un tutoriel existant svp?
Ou si c'est possible pouvez mettre à disposition la liste des noms de champs obligatoires?

Merci!

**Comment by Ailurupoda** [comment]
Je dirais que le plus simple est d'utiliser directement les données Edigeo qui était le choix vers lequel s'est tourné le développement de ce plugin.

Toutefois, une autre source de données peut fonctionner du moment que les champs équivalents sont bien présents. Vous pouvez donc continuer à modifier les champs des données sources.

Pour savoir les champs nécessaire, vous pouvez rentrer dans le code directement et essayer de chercher (Les champs sont spécifié dans les commandes de la fonction **createSocle** ligne 638).

Je rajouterais dans le documentation le formatage pré-requis des données.

**Comment by sylvain0** [comment]
D'accord merci!
